### ISSUE TITLE
Add bokeh_fastapi as a meta package 

### ISSUE THREAD

**Issue by hoxbro** [conda-forge/bokeh-fastapi-feedstock#1]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

For PyPi it does not make any difference between the -/_, whereas it does for conda. 

So it could be nice to add meta package for bokeh_fastapi. I did the same with `ipywidget-bokeh`, see [here](https://github.com/conda-forge/ipywidgets-bokeh-feedstock/blob/main/recipe/meta.yaml).

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by pmeier** [comment]
Sure, that sounds like a good idea. However, instead of hardcoding the name of the meta package, could we do something like `{{ name | replace("_", "-") }}` (or the other way around depending on how we define the `name`)? IMO, this makes the intention a little more clear.

@hoxbro Do you want to send a PR?

**Comment by hoxbro** [comment]
> could we do something like {{ name | replace("_", "-") }}

That is up to you. We only really need an explicit name in the meta package's name. 

> Do you want to send a PR?

I will make one. Which should the main package name: `bokeh-fastapi` or `bokeh_fastapi`

**Comment by pmeier** [comment]
> We only really need an explicit name in the meta package's name.

Fair enough. But please add a comment on why this is there if the intention is not expressed as code.

> Which should the main package name: `bokeh-fastapi` or `bokeh_fastapi`

I prefer `bokeh-fastapi` as this is what we have in the project slug, i.e. https://github.com/bokeh/bokeh-fastapi, as well. However, our [`pyproject.toml`](https://github.com/bokeh/bokeh-fastapi/blob/2aa0f4dcad4cf5e7f57c93166dd5af956b80c294/pyproject.toml#L8-L9) currently uses `bokeh_fastapi`.

We should get rid of this inconsistency. I guess there are not terribly many links yet, but still changing the project name and thus URL is more disruptive than some metadata.
